project:
  type: website

website:
  title: "myfeed"
  navbar:
    right:
      - about.qmd
      - feed.qmd
      - icon: github
        href: https://github.com/leesahanders/rss_feed
format:
  html:
    theme: cosmo
    css: styles.css



