project:
  type: website

website:
  title: "questionable.quarto"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/leesahanders/rss_feed
format:
  html:
    theme: vapor
    css: styles.css



