project:
  type: website

website:
  site-url: "https://questionable.quarto.pub/blog/"
  title: "questionable.quarto"
  navbar:
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        icon: fa-database
        menu:
          - text: "Posts"
            href: posts.qmd
          - text: "Presentations"
            href: presentations.qmd            
          - text: "Recipes"
            href: https://questionable.quarto.pub/recipes/
      - text: "Posts"
        href: posts.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Recipes"
        href: https://questionable.quarto.pub/recipes/

    right:
      - about.qmd
      - text: "Site Map"
        href: site_map.qmd
      - icon: github
        href: https://github.com/leesahanders/my_website
format:
  html:
    theme: 
      light: [litera, custom_theme.scss]
      dark: [vapor, custom_theme.scss]
    css: styles.css

