project:
  type: website

website:
  title: "questionable.quarto"
  navbar:
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Projects"
        icon: fa-database
        menu:
          - text: "Resin Dice"
            href: resin.qmd
          - text: "Recipes"
            href: recipes.qmd

    right:
      - about.qmd
      - icon: github
        href: https://github.com/leesahanders/my_website
format:
  html:
    theme: 
      light: custom_theme.scss
      dark: vapor
    css: styles.css

