project:
  type: website

website:
  site-url: "https://questionable.quarto.pub/blog/"
  title: "Lisa Anders - questionable.quarto"
  description: "Making the most out of data"
  navbar:
    title: "<span class='icon-upper'>LISA ANDERS</span><span class='icon-sep'></span><span class='icon-lower'>questionable.quarto</span>"
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Stuff"
        icon: fa-database
        menu:
          - text: "Blog posts"
            href: posts.qmd
          - text: "Lists"
            href: lists.qmd         
          - text: "Presentations"
            href: presentations.qmd   
          - text: "Recipes"
            href: https://questionable.quarto.pub/recipes/
          - text: "Technical writeups"
            href: work.qmd  

    right:
      - about.qmd
      - text: "Site Map"
        href: site_map.qmd
      - icon: github
        href: https://github.com/leesahanders/my_website
format:
  html:
    theme: 
      light: [litera, custom_theme.scss]
      dark: [vapor, theme-dark.scss]
    css: styles.css

